# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
org.gradle.jvmargs=-Xmx8G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

parchment_minecraft_version=1.21.1
parchment_mappings_version=2024.11.17

minecraft_version=1.21.1
minecraft_version_range=[1.21.1]
neo_version=21.1.211
loader_version_range=[1,)

## Mod Properties
mod_id=theveil
mod_name=The Veil Mod
mod_license=All Rights Reserved
mod_version=0.0.2
mod_group_id=com.trist79.veil
mod_authors=Tristan Anderson
mod_description=Step into The Veil, a mysterious, ever-shifting dimension filled with echoes, illusions, and hidden secrets.
